package com.modafa.sp.dna.uaa.security;

/**
 * Constants for Spring Security authorities.
 */
public final class AuthoritiesConstants {

    // ROLES
    public static final String ADMIN = "ROLE_ADMIN";

    public static final String USER = "ROLE_USER";

    public static final String ANONYMOUS = "ROLE_ANONYMOUS";

    public static final String ROLE_DNA_USER = "ROLE_DNA_USER";

    public static final String ROLE_ASAC_USER = "ROLE_ASAC_USER";

    public static final String ROLE_POOL_TPV_USER = "ROLE_POOL_TPV_USER";

    public static final String ROLE_INSURANCECOMPANY_USER = "ROLE_INSURANCECOMPANY_USER";

    public static final String ROLE_INSURANCECOMPANY_BROKER_USER = "ROLE_INSURANCECOMPANY_BROKER_USER";

    // PRIVILEDGES
    public static final String INSURANCECOMPANY_CREATE = "INSURANCECOMPANY_CREATE";

    public static final String INSURANCECOMPANY_READ = "INSURANCECOMPANY_READ";

    public static final String INSURANCECOMPANY_WRITE = "INSURANCECOMPANY_WRITE";

    public static final String INSURANCECOMPANY_DELETE = "INSURANCECOMPANY_DELETE";

    public static final String ATTACHEDDOCUMENT_CREATE = "ATTACHEDDOCUMENT_CREATE";

    public static final String ATTACHEDDOCUMENT_READ = "ATTACHEDDOCUMENT_READ";

    public static final String ATTACHEDDOCUMENT_WRITE = "ATTACHEDDOCUMENT_WRITE";

    public static final String ATTACHEDDOCUMENT_DELETE = "ATTACHEDDOCUMENT_DELETE";

    public static final String INSURANCEBROKER_CREATE = "INSURANCEBROKER_CREATE";

    public static final String INSURANCEBROKER_READ = "INSURANCEBROKER_READ";

    public static final String INSURANCEBROKER_WRITE = "INSURANCEBROKER_WRITE";

    public static final String INSURANCEBROKER_DELETE = "INSURANCEBROKER_DELETE";

    public static final String CLIENT_CREATE = "CLIENT_CREATE";

    public static final String CLIENT_READ = "CLIENT_READ";

    public static final String CLIENT_WRITE = "CLIENT_WRITE";

    public static final String CLIENT_DELETE = "CLIENT_DELETE";

    public static final String ADDRESS_CREATE = "ADDRESS_CREATE";

    public static final String ADDRESS_READ = "ADDRESS_READ";

    public static final String ADDRESS_WRITE = "ADDRESS_WRITE";

    public static final String ADDRESS_DELETE = "ADDRESS_DELETE";

    public static final String INSURANCECERTIFICATE_CREATE = "INSURANCECERTIFICATE_CREATE";

    public static final String INSURANCECERTIFICATE_READ = "INSURANCECERTIFICATE_READ";

    public static final String INSURANCECERTIFICATE_WRITE = "INSURANCECERTIFICATE_WRITE";

    public static final String INSURANCECERTIFICATE_DELETE = "INSURANCECERTIFICATE_DELETE";

    public static final String COUNTRY_CREATE = "COUNTRY_CREATE";

    public static final String COUNTRY_READ = "COUNTRY_READ";

    public static final String COUNTRY_WRITE = "COUNTRY_WRITE";

    public static final String COUNTRY_DELETE = "COUNTRY_DELETE";

    public static final String VEHICLE_CREATE = "VEHICLE_CREATE";

    public static final String VEHICLE_READ = "VEHICLE_READ";

    public static final String VEHICLE_WRITE = "VEHICLE_WRITE";

    public static final String VEHICLE_DELETE = "VEHICLE_DELETE";

    public static final String INSURANCESALE_CREATE = "INSURANCESALE_CREATE";

    public static final String INSURANCESALE_READ = "INSURANCESALE_READ";

    public static final String INSURANCESALE_WRITE = "INSURANCESALE_WRITE";

    public static final String INSURANCESALE_DELETE = "INSURANCESALE_DELETE";

    public static final String INSURANCECOMPANYCERTIFICATEORDER_CREATE = "INSURANCECOMPANYCERTIFICATEORDER_CREATE";

    public static final String INSURANCECOMPANYCERTIFICATEORDER_READ = "INSURANCECOMPANYCERTIFICATEORDER_READ";

    public static final String INSURANCECOMPANYCERTIFICATEORDER_WRITE = "INSURANCECOMPANYCERTIFICATEORDER_WRITE";

    public static final String INSURANCECOMPANYCERTIFICATEORDER_DELETE = "INSURANCECOMPANYCERTIFICATEORDER_DELETE";

    public static final String INSURANCECERTIFICATETRANSFER_CREATE = "INSURANCECERTIFICATETRANSFER_CREATE";

    public static final String INSURANCECERTIFICATETRANSFER_READ = "INSURANCECERTIFICATETRANSFER_READ";

    public static final String INSURANCECERTIFICATETRANSFER_WRITE = "INSURANCECERTIFICATETRANSFER_WRITE";

    public static final String INSURANCECERTIFICATETRANSFER_DELETE = "INSURANCECERTIFICATETRANSFER_DELETE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDER_CREATE = "INSURANCECERTIFICATEPRINTERDELIVERYORDER_CREATE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDER_READ = "INSURANCECERTIFICATEPRINTERDELIVERYORDER_READ";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDER_WRITE = "INSURANCECERTIFICATEPRINTERDELIVERYORDER_WRITE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDER_DELETE = "INSURANCECERTIFICATEPRINTERDELIVERYORDER_DELETE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_CREATE = "INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_CREATE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_READ = "INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_READ";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_WRITE = "INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_WRITE";

    public static final String INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_DELETE = "INSURANCECERTIFICATEPRINTERDELIVERYORDERLINE_DELETE";

    public static final String INSURANCEDISASTER_CREATE = "INSURANCEDISASTER_CREATE";

    public static final String INSURANCEDISASTER_READ = "INSURANCEDISASTER_READ";

    public static final String INSURANCEDISASTER_WRITE = "INSURANCEDISASTER_WRITE";

    public static final String INSURANCEDISASTER_DELETE = "INSURANCEDISASTER_DELETE";

    public static final String IMPORTANTNOTEANDREMARK_CREATE = "IMPORTANTNOTEANDREMARK_CREATE";

    public static final String IMPORTANTNOTEANDREMARK_READ = "IMPORTANTNOTEANDREMARK_READ";

    public static final String IMPORTANTNOTEANDREMARK_WRITE = "IMPORTANTNOTEANDREMARK_WRITE";

    public static final String IMPORTANTNOTEANDREMARK_DELETE = "IMPORTANTNOTEANDREMARK_DELETE";

    private AuthoritiesConstants() {
    }
}
